package ee.ioc.cs.vsle.ccl;

/*-
 * #%L
 * CoCoViLa
 * %%
 * Copyright (C) 2003 - 2017 Institute of Cybernetics at Tallinn University of Technology
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

/**
 * <p>Title: CompileException</p>
 * <p>Description: An exception that is thrown when a compilation
 * error occurs. The error message generated by the compiler is
 * included for debugging.</p>
 */
public class CompileException extends RuntimeException {

    private static final long serialVersionUID = 1L;

    /**
     * Class constructor.
     * @param msg exception message.
     */
    CompileException(String msg) {
        super(msg);
    }
}
