package ee.ioc.cs.vsle.ccl;

/**
 * <p>Title: CompileException</p>
 * <p>Description: An exception that is thrown when a compilation
 * error occurs. The error message generated by the compiler is
 * included for debugging.</p>
 * <p>Copyright: Copyright (c) 2004</p>
 * @author Ando Saabas
 * @version 1.0
 */
public class CompileException extends RuntimeException {

	private static final long serialVersionUID = 1L;

	/**
	 * Exception description.
	 */
	public String excDesc;

	/**
	 * Class constructor.
	 * @param msg exception message.
	 */
	CompileException(String msg) {
		excDesc = msg;
	} // ee.ioc.cs.editor.ccl.CompileException

}