package ee.ioc.cs.vsle.ccl;

/**
 * <p>Title: CompileException</p>
 * <p>Description: An exception that is thrown when a compilation
 * error occurs. The error message generated by the compiler is
 * included for debugging.</p>
 */
public class CompileException extends RuntimeException {

    private static final long serialVersionUID = 1L;

    /**
     * Class constructor.
     * @param msg exception message.
     */
    CompileException(String msg) {
        super(msg);
    }
}